from pathlib import Path
import numpy as np, pandas as pd, matplotlib.pyplot as plt, random
from matplotlib.patches import Rectangle, Circle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.metrics import confusion_matrix, roc_curve, auc, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from skimage import data, transform, color
from scipy.signal import convolve2d
from skimage.registration import optical_flow_tvl1
import argparse
_parser=argparse.ArgumentParser(); _parser.add_argument('--package-root',required=True); _args=_parser.parse_args(); ROOT=Path(_args.package_root)
audit=pd.read_csv(ROOT/'Master_QA_Audit_Pass13.csv'); inv=pd.read_csv(ROOT/'Frozen_Figure_Inventory_Master_Pass13.csv')
NAVY='#243447';TEAL='#2A6F73';ORANGE='#B66A3C';VIOLET='#756B8A';SLATE='#6B7280';LIGHT='#D9DEE5';RED='#9A4D4D';COLORS=[NAVY,TEAL,ORANGE,VIOLET,'#A88B4A','#4E6E8E',RED,'#557A5E']
plt.rcParams.update({'font.size':9,'axes.spines.top':False,'axes.spines.right':False,'savefig.facecolor':'white'});np.random.seed(14);random.seed(14)
def row(ch,f): return audit[(audit.chapter==ch)&(audit.figure_number==f)].iloc[0]
def asset(ch,f): return ROOT/ch/row(ch,f).asset
def save(ch,f,fig):
 p=asset(ch,f);p.parent.mkdir(parents=True,exist_ok=True);fig.savefig(p,dpi=240,bbox_inches='tight',pad_inches=.025);plt.close(fig)
def panel(ax,s): ax.text(.5,-.12,s,transform=ax.transAxes,ha='center',va='top',fontsize=9)
def clean(ax): ax.grid(False);ax.tick_params(direction='out',length=3)
def update(ch,f,title,caption,reason,prov,kind):
 m=(audit.chapter==ch)&(audit.figure_number==f);audit.loc[m,'audit_status']='ACCEPT';audit.loc[m,'audit_reason']=reason;audit.loc[m,'provenance']=prov
 if 'title' in audit.columns:audit.loc[m,'title']=title
 if 'caption' in audit.columns:audit.loc[m,'caption']=caption
 mi=(inv.chapter==ch)&(inv.figure_number==f);inv.loc[mi,'audit_status']='ACCEPT';inv.loc[mi,'audit_reason']=reason;inv.loc[mi,'provenance']=prov;inv.loc[mi,'title']=title;inv.loc[mi,'caption']=caption
 if 'production_class' in inv.columns:inv.loc[mi,'production_class']=kind
 rem.append((f,title))
rem=[];ch='03_Deep_Learning_Part_I'
# Figure 7: public AirPassengers sequence experiment.
f=7
air=np.array([112,118,132,129,121,135,148,148,136,119,104,118,115,126,141,135,125,149,170,170,158,133,114,140,145,150,178,163,172,178,199,199,184,162,146,166,171,180,193,181,183,218,230,242,209,191,172,194,196,196,236,235,229,243,264,272,237,211,180,201,204,188,235,227,234,264,302,293,259,229,203,229,242,233,267,269,270,315,364,347,312,274,237,278,284,277,317,313,318,374,413,405,355,306,271,306,315,301,356,348,355,422,465,467,404,347,305,336,340,318,362,348,363,435,491,505,404,359,310,337,360,342,406,396,420,472,548,559,463,407,362,405,417,391,419,461,472,535,622,606,508,461,390,432],dtype=np.float32)
lag=12;X=np.array([air[i:i+lag] for i in range(len(air)-lag)]);y=np.array([air[i+lag] for i in range(len(air)-lag)]);split=100;sc=StandardScaler().fit(X[:split]);model=Ridge(alpha=10).fit(sc.transform(X[:split]),y[:split]);pred=model.predict(sc.transform(X[split:]));rmse=float(np.sqrt(np.mean((pred-y[split:])**2)));loss=[]
for n in range(24,split+1,2):
 m=Ridge(alpha=10).fit(sc.transform(X[:n]),y[:n]);pp=m.predict(sc.transform(X[:n]));loss.append(np.sqrt(np.mean((pp-y[:n])**2)))
fig,axs=plt.subplots(1,2,figsize=(8.4,3));axs[0].plot(np.arange(len(loss))*2+24,loss);axs[0].set_xlabel('Training samples used');axs[0].set_ylabel('Training RMSE');clean(axs[0]);panel(axs[0],'(a)');axs[1].plot(y[split:],label='observed');axs[1].plot(pred,label='forecast');axs[1].set_xlabel('Held-out month');axs[1].set_ylabel('Passengers (thousands)');axs[1].legend(frameon=False,fontsize=7);clean(axs[1]);panel(axs[1],'(b)');fig.tight_layout();save(ch,f,fig)
update(ch,f,'AirPassengers sequence forecasting with a reproducible lag model','Forecasting experiment on the classic monthly international-airline-passenger series. (a) Training RMSE as the fitting set expands under a fixed 12-month lag representation. (b) held-out forecasts against observed passenger counts. The measured held-out RMSE for this exact implementation is reported in the provenance record rather than retaining the unsupported legacy value of 32.46.','Pass 14 actual public-series experiment; legacy 2000-epoch/final-RMSE claim removed.','Classic AirPassengers monthly series embedded verbatim; Ridge lag-12 model; held-out RMSE %.2f.'%rmse,'REPRODUCIBLE PUBLIC-DATA EXPERIMENT')
# Figure 11: HAR signals.
f=11;t=np.linspace(0,6,600);walk=np.sin(2*np.pi*1.8*t)+.25*np.sin(2*np.pi*3.6*t);still=.08*np.sin(2*np.pi*.3*t);run=1.4*np.sin(2*np.pi*3*t)+.35*np.sin(2*np.pi*6*t);fig,axs=plt.subplots(1,2,figsize=(8.3,3));axs[0].plot(t,still,label='stationary');axs[0].plot(t,walk,label='walking');axs[0].plot(t,run,label='running');axs[0].set_xlabel('time (s)');axs[0].set_ylabel('normalized acceleration');axs[0].legend(frameon=False,fontsize=7);clean(axs[0]);panel(axs[0],'(a)')
for sig,c,l in [(still,NAVY,'stationary'),(walk,TEAL,'walking'),(run,ORANGE,'running')]:
 sp=np.abs(np.fft.rfft(sig));fr=np.fft.rfftfreq(len(sig),t[1]-t[0]);axs[1].plot(fr,sp/sp.max(),label=l,color=c)
axs[1].set_xlim(0,8);axs[1].set_xlabel('frequency (Hz)');axs[1].set_ylabel('normalized spectrum');clean(axs[1]);panel(axs[1],'(b)');fig.tight_layout();save(ch,f,fig)
update(ch,f,'Sensor time-series and spectral structure for human-activity recognition','Code-generated inertial-sensor example for human-activity recognition. (a) representative stationary, walking, and running acceleration signals generated from explicit harmonic motion models. (b) normalized frequency spectra of the same signals, showing the increasing dominant cadence and harmonic content used by temporal classifiers.','Pass 14 fills previously captionless HAR figure with an explicit numerical model.','Deterministic inertial-signal simulation and FFT.','NUMERICAL SIGNAL EXPERIMENT')
# Figures 22,25,27: cyclone morphology/intensity reconstruction.
def cyclone_field(strength=1.,phase=0):
 n=180;yy,xx=np.mgrid[-1:1:complex(n),-1:1:complex(n)];r=np.hypot(xx,yy);th=np.arctan2(yy,xx);band=np.exp(-((r-.48)/.22)**2)*(.55+.45*np.cos(4*(th+2.7*r)+phase));eye=np.exp(-(r/.12)**2);return strength*(band+.25*np.exp(-(r/.65)**2)-.8*eye)
for f in [22,25,27]:
 if f==22:
  fig,axs=plt.subplots(1,4,figsize=(8.8,2.2));
  for i,(ax,s) in enumerate(zip(axs,[.55,.75,.95,1.15])):ax.imshow(cyclone_field(s,i*.45),cmap='gray');ax.axis('off');panel(ax,f'({chr(97+i)})')
  title='Physics-inspired tropical-cyclone morphology sequence';cap='Four deterministic cyclone cloud-field reconstructions illustrating increasing organization, eye definition, and spiral-band contrast under a controlled analytic vortex model. The panels are explanatory scientific renderings and are not represented as U.S. Naval Research Laboratory satellite images.'
 elif f==25:
  fig,axs=plt.subplots(1,5,figsize=(9,2.1));labs=['TD','TS','H1','H3','H5']
  for i,(ax,s,l) in enumerate(zip(axs,[.45,.6,.78,1,1.25],labs)):ax.imshow(cyclone_field(s,i*.3),cmap='gray');ax.axis('off');ax.text(.5,.02,l,transform=ax.transAxes,ha='center',fontsize=8);panel(ax,f'({chr(97+i)})')
  title='Controlled cyclone-intensity class exemplars';cap='Physics-inspired cloud-field exemplars assigned to increasing intensity classes from tropical depression through major hurricane. The morphology is generated by an explicit analytic vortex model; the labels illustrate the classification task and are not asserted to be satellite observations from a particular storm archive.'
 else:
  winds=np.array([30,40,55,70,85,105,125,150]);radii=np.array([.65,.62,.59,.55,.49,.43,.36,.29]);fig,axs=plt.subplots(1,2,figsize=(7.8,3));axs[0].plot(winds,radii,marker='o');axs[0].set_xlabel('maximum sustained wind (kt)');axs[0].set_ylabel('normalized eye/core radius');clean(axs[0]);panel(axs[0],'(a)');axs[1].imshow(cyclone_field(1.15,.3),cmap='gray');axs[1].axis('off');panel(axs[1],'(b)');title='Numerical hurricane-intensity feature model';cap='Numerical hurricane-intensity feature model linking increasing maximum sustained wind to a tightening analytic vortex core. (a) prescribed wind–core relationship used by the model. (b) representative high-intensity cloud-field reconstruction. This figure replaces a captionless placeholder and does not claim empirical satellite retrieval.'
 fig.tight_layout();save(ch,f,fig);update(ch,f,title,cap,'Pass 14 deterministic cyclone numerical model.','Analytic vortex/cloud-band model with explicit intensity parameter.','NUMERICAL SCIENTIFIC RECONSTRUCTION')
# Figure 28: controlled classifier.
f=28;rng=np.random.default_rng(28);classes=np.arange(8);n=1600;yy=rng.integers(0,8,n);X=np.c_[yy+rng.normal(0,.9,n),np.sin(yy)+rng.normal(0,.5,n),rng.normal(yy*.25,.7,n)];Xt,Xs,yt,ys=train_test_split(X,yy,test_size=.3,random_state=28,stratify=yy);cyclone_clf=RandomForestClassifier(120,random_state=28).fit(Xt,yt);ypc=cyclone_clf.predict(Xs);cm=confusion_matrix(ys,ypc,labels=classes,normalize='true');fig,ax=plt.subplots(figsize=(5.6,4.5));im=ax.imshow(cm,vmin=0,vmax=1,cmap='viridis');labs=['NC','TD','TS','H1','H2','H3','H4','H5'];ax.set_xticks(classes,labs);ax.set_yticks(classes,labs);ax.set_xlabel('predicted');ax.set_ylabel('true');fig.colorbar(im,ax=ax,fraction=.04,pad=.03,label='row-normalized fraction');fig.tight_layout();save(ch,f,fig)
update(ch,f,'Controlled hurricane-intensity confusion matrix','Row-normalized confusion matrix from a reproducible eight-class controlled hurricane-intensity experiment. The classifier is trained on numerically generated intensity features with known labels, allowing systematic adjacent-category confusion to be examined without presenting synthetic values as satellite-benchmark performance.','Pass 14 actual controlled classification experiment.','Random-forest classifier on deterministic simulated cyclone-intensity features, seed 28.','CONTROLLED NUMERICAL EXPERIMENT')
# Figures 29-31: convolution computation on public image.
sample=transform.resize(data.chelsea(),(32,32),anti_aliasing=True);f=29;fig,ax=plt.subplots(figsize=(3.3,3.3));ax.imshow(sample);ax.axis('off');fig.tight_layout();save(ch,f,fig)
update(ch,f,'32×32 RGB sample used for convolution feature-map analysis','A 32×32 RGB public reference image used as the fixed input to the subsequent convolutional feature-map computation. The original CIFAR-10-specific claim is removed because the available production environment did not contain the CIFAR-10 training corpus; the image source and preprocessing are fully reproducible.','Pass 14 replaces unsupported CIFAR-10 sample claim.','scikit-image public Chelsea image resized to 32×32.','PUBLIC-IMAGE COMPUTATION')
gray=color.rgb2gray(sample);kernels=[np.array([[-1,0,1],[-2,0,2],[-1,0,1]]),np.array([[-1,-2,-1],[0,0,0],[1,2,1]]),np.array([[0,1,0],[1,-4,1],[0,1,0]]),np.ones((3,3))/9];maps2=[np.maximum(0,convolve2d(gray,k,mode='same',boundary='symm')) for k in kernels]
f=30;fig,axs=plt.subplots(1,4,figsize=(8.5,2.2))
for i,(ax,A) in enumerate(zip(axs,maps2)):ax.imshow(A,cmap='viridis');ax.axis('off');panel(ax,f'({chr(97+i)})')
fig.tight_layout();save(ch,f,fig);update(ch,f,'First-block convolution feature responses','Four feature responses computed from the fixed 32×32 input using explicit first-layer convolution kernels followed by ReLU: vertical edge, horizontal edge, Laplacian-like detail, and local averaging. This reproducible calculation replaces the unsupported claim that the maps came from a particular trained CIFAR-10 CNN.','Pass 14 exact convolution computation.','Public input image; explicit 3×3 kernels and ReLU.','CODED SCIENTIFIC COMPUTATION')
f=31;fig,axs=plt.subplots(1,3,figsize=(7.5,2.4));axs[0].imshow(maps2[0],cmap='viridis');axs[1].imshow(transform.resize(maps2[0],(16,16)),cmap='viridis');rng=np.random.default_rng(31);drop=maps2[0].copy();drop[rng.random(drop.shape)<.35]=0;axs[2].imshow(drop,cmap='viridis')
for i,a in enumerate(axs):a.axis('off');panel(a,f'({chr(97+i)})')
fig.tight_layout();save(ch,f,fig);update(ch,f,'Activation, pooling, and dropout effects in a convolutional block','Controlled view of three transformations applied to the same convolution response: (a) activated feature map, (b) spatially reduced representation, and (c) a fixed-seed dropout realization. The panels make the block-level computation explicit and replace the previous captionless placeholder.','Pass 14 exact image-tensor transformations.','Public sample image; deterministic convolution, resize pooling proxy, fixed-seed dropout mask.','CODED SCIENTIFIC COMPUTATION')
# Figures 32,34,35,41,42: public digits classifier.
from sklearn.datasets import load_digits
D=load_digits();Xd=D.data/16;yd=D.target;Xtr,Xte,ytr,yte=train_test_split(Xd,yd,test_size=.25,random_state=14,stratify=yd);clf=LogisticRegression(max_iter=1500).fit(Xtr,ytr);yp=clf.predict(Xte);prob=clf.predict_proba(Xte)
f=32;fig,axs=plt.subplots(2,6,figsize=(7.8,3))
for i,a in enumerate(axs.flat):a.imshow(Xtr[i].reshape(8,8),cmap='gray');a.axis('off');a.text(.5,.02,str(ytr[i]),transform=a.transAxes,ha='center',fontsize=8)
fig.tight_layout();save(ch,f,fig);update(ch,f,'Public handwritten-digit samples with ground-truth labels','Twelve handwritten-digit samples from the public scikit-learn digits dataset with ground-truth labels. This replaces the unsupported MNIST-specific provenance while preserving the pedagogical role of showing handwriting variability before classification.','Pass 14 actual public dataset.','scikit-learn digits dataset.','PUBLIC-DATA RENDERING')
f=34;fig,axs=plt.subplots(2,6,figsize=(7.8,3))
for i,a in enumerate(axs.flat):a.imshow(Xte[i].reshape(8,8),cmap='gray');a.axis('off');a.text(.5,.02,f'{yp[i]} ({prob[i,yp[i]]:.2f})',transform=a.transAxes,ha='center',fontsize=7)
fig.tight_layout();save(ch,f,fig);update(ch,f,'Held-out handwritten-digit predictions with confidence','Held-out public handwritten-digit images with the reproducible classifier prediction and predicted-class probability shown below each image. The experiment uses the scikit-learn digits dataset and a multinomial logistic-regression classifier with a fixed split.','Pass 14 actual public-data prediction experiment.','scikit-learn digits; 75/25 stratified split; logistic regression.','REPRODUCIBLE PUBLIC-DATA EXPERIMENT')
f=35;cm2=confusion_matrix(yte,yp,normalize='true');fig,axs=plt.subplots(1,2,figsize=(7.8,3));im=axs[0].imshow(cm2,vmin=0,vmax=1,cmap='viridis');axs[0].set_xlabel('predicted');axs[0].set_ylabel('true');fig.colorbar(im,ax=axs[0],fraction=.04,pad=.03);axs[1].hist(prob.max(1),bins=np.linspace(.2,1,17));axs[1].set_xlabel('maximum predicted probability');axs[1].set_ylabel('held-out samples');clean(axs[1]);panel(axs[0],'(a)');panel(axs[1],'(b)');fig.tight_layout();save(ch,f,fig)
update(ch,f,'Held-out digit-classification diagnostics','Reproducible held-out diagnostics for the public digits classification experiment. (a) row-normalized confusion matrix. (b) distribution of maximum predicted class probability. These measured outputs replace the previous captionless application placeholder.','Pass 14 actual classifier diagnostics.','Same scikit-learn digits/logistic-regression experiment as Figure 34; held-out accuracy %.3f.'%accuracy_score(yte,yp),'REPRODUCIBLE PUBLIC-DATA EXPERIMENT')
for f,idxs in [(41,[20,31,45,57,63,88]),(42,[5,15,25,35,55,75])]:
 fig,axs=plt.subplots(1,6,figsize=(7.8,1.55))
 for a,i in zip(axs,idxs):a.imshow(Xte[i].reshape(8,8),cmap='gray');a.axis('off');a.text(.5,.02,f't={yte[i]}, p={yp[i]}',transform=a.transAxes,ha='center',fontsize=6.5)
 fig.tight_layout();save(ch,f,fig);update(ch,f,f'Held-out prediction examples, set {1 if f==41 else 2}',f'Six held-out handwritten-digit predictions from the reproducible public digits experiment. Each panel reports the true label t and predicted label p, providing concrete examples of correct and incorrect unseen-image predictions without relying on untraceable legacy screenshots.','Pass 14 actual held-out examples.','scikit-learn digits/logistic-regression held-out predictions.','REPRODUCIBLE PUBLIC-DATA EXPERIMENT')
# Figure 43: generic top-k uncertainty illustration.
f=43;names=['class A','class B','class C','class D','class E'];vals=np.array([.52,.21,.13,.09,.05]);fig,axs=plt.subplots(1,2,figsize=(7.4,2.9));axs[0].imshow(data.chelsea());axs[0].axis('off');axs[1].barh(names[::-1],vals[::-1],color=TEAL);axs[1].set_xlabel('normalized top-k score');clean(axs[1]);panel(axs[0],'(a)');panel(axs[1],'(b)');fig.tight_layout();save(ch,f,fig)
update(ch,f,'Unseen-image top-k classification example','Public-image example used to illustrate top-k prediction uncertainty in a transfer-learning workflow. (a) input image. (b) normalized top-k class-score distribution. The class labels are deliberately generic because no reproducible dog-breed model checkpoint accompanied the legacy figure; the replacement does not claim breed-level empirical performance.','Pass 14 removes unsupported dog-breed model claim.','Public scikit-image Chelsea image; normalized illustrative score vector.','NON-EMPIRICAL MODEL-OUTPUT EXPLANATION')
# Figures 54-55: actual dense optical flow.
for f,img0,name in [(54,transform.resize(data.camera(),(180,240)),'driving-like grayscale reference'),(55,color.rgb2gray(transform.resize(data.astronaut(),(180,240))),'complex-motion reference')]:
 shifted=np.roll(img0,shift=(4,7),axis=(0,1));v,u=optical_flow_tvl1(img0,shifted);mag=np.hypot(u,v);fig,axs=plt.subplots(1,3,figsize=(9,2.7));axs[0].imshow(img0,cmap='gray');axs[1].imshow(shifted,cmap='gray');im=axs[2].imshow(mag,cmap='viridis');fig.colorbar(im,ax=axs[2],fraction=.04,pad=.03,label='flow magnitude')
 for i,a in enumerate(axs):a.axis('off');panel(a,f'({chr(97+i)})')
 fig.tight_layout();save(ch,f,fig);title='Dense optical-flow prediction on a controlled public-image pair' if f==54 else 'Dense optical-flow prediction under a controlled complex-image warp';cap=f'Controlled dense optical-flow experiment using a public {name}. (a) first frame, (b) deterministically translated second frame, and (c) TV-L1 dense-flow magnitude estimated from the pair. The figure replaces the unsupported claim that the production asset reproduces the RAFT KITTI/Sintel test-set figure; RAFT benchmark results remain cited in the text separately.';update(ch,f,title,cap,'Pass 14 actual optical-flow computation on public images.','scikit-image public image; deterministic translation; skimage.registration.optical_flow_tvl1.','REPRODUCIBLE PUBLIC-IMAGE EXPERIMENT')
# Figures 56-58: copyright-safe style-transfer mechanics.
base=color.rgb2gray(transform.resize(data.astronaut(),(180,240)));xx=np.linspace(0,1,240);style=np.sin(10*np.pi*xx)[None,:]*np.ones((180,1));styled=np.clip(base+.22*style,0,1)
for f in [56,57,58]:
 if f==56:fig,axs=plt.subplots(1,2,figsize=(7.4,2.8));axs[0].imshow(base,cmap='gray');axs[1].imshow(styled,cmap='magma')
 elif f==57:fig,axs=plt.subplots(1,3,figsize=(8.4,2.7));axs[0].imshow(base,cmap='gray');axs[1].imshow(styled,cmap='magma');axs[2].imshow(.5*styled+.5*base,cmap='magma')
 else:
  fig,axs=plt.subplots(1,3,figsize=(8.4,2.7));prev=np.roll(styled,4,axis=1);ind=np.clip(base+.22*np.roll(style,4,axis=1),0,1);temp=.65*prev+.35*ind;axs[0].imshow(prev,cmap='magma');axs[1].imshow(ind,cmap='magma');axs[2].imshow(temp,cmap='magma')
 for i,a in enumerate(axs):a.axis('off');panel(a,f'({chr(97+i)})')
 fig.tight_layout();save(ch,f,fig);titles={56:'Controlled image-to-style transformation',57:'Multi-pass style-refinement reconstruction',58:'Temporal-consistency comparison for stylized frames'};caps={56:'Controlled style-transformation example on a public reference image. The style field is an explicit spatial texture signal added to the image representation; no copyrighted film frame or painting reproduction is used.',57:'Three-stage style-refinement reconstruction on the same public reference image: source, first stylization pass, and blended refinement pass. The panel explains multi-pass style processing without reproducing the Miss Mabel source figure.',58:'Temporal-consistency experiment for stylized frames. The panels compare a previous stylized frame, an independently processed translated frame, and temporal blending that reduces frame-to-frame variation. This replaces the copyrighted Ice Age/Starry Night example while preserving the algorithmic comparison.'};update(ch,f,titles[f],caps[f],'Pass 14 copyright-safe algorithmic reconstruction.','Public scikit-image reference image plus deterministic texture/stylization transforms.','CODED SCIENTIFIC RECONSTRUCTION')
# Figures 60-62: controlled hurricane pipeline and diagnostics.
f=60;fig,axs=plt.subplots(1,4,figsize=(9.2,2.4));axs[0].imshow(cyclone_field(.9,.2),cmap='gray');axs[0].axis('off');wind=np.array([35,45,60,75,90,110,130]);axs[1].plot(wind,marker='o');axs[1].set_ylabel('wind (kt)');axs[2].plot(np.gradient(wind),marker='o');axs[2].set_ylabel('Δ wind');axs[3].bar(range(8),np.bincount(yy,minlength=8)/len(yy));axs[3].set_ylabel('class fraction')
for i,a in enumerate(axs):panel(a,f'({chr(97+i)})')
fig.tight_layout();save(ch,f,fig);update(ch,f,'Reproducible hurricane-intensity estimation workflow','Four-stage reproducible hurricane-intensity workflow: (a) code-generated cyclone field, (b) time-ordered wind-intensity observations, (c) derived temporal-change features, and (d) class-distribution output for the controlled eight-category classifier. The workflow is explicitly numerical and does not claim unverified satellite/HURDAT2 image alignment.','Pass 14 actual numerical pipeline.','Analytic cyclone field plus controlled intensity-series features and classifier.','NUMERICAL APPLICATION PIPELINE')
f=61;fig,ax=plt.subplots(figsize=(5.6,4.5));im=ax.imshow(cm,vmin=0,vmax=1,cmap='viridis');ax.set_xticks(classes);ax.set_yticks(classes);ax.set_xlabel('predicted class');ax.set_ylabel('true class');fig.colorbar(im,ax=ax,fraction=.04,pad=.03);fig.tight_layout();save(ch,f,fig);update(ch,f,'Controlled hurricane-classification confusion matrix','Confusion matrix from the same reproducible controlled eight-class hurricane-intensity experiment used in the application pipeline. Because the labels are generated by a known numerical model, the matrix is valid evidence for the controlled experiment but is not presented as performance on a satellite benchmark.','Pass 14 exact reuse of controlled classifier outputs.','Random-forest controlled cyclone-intensity experiment.','CONTROLLED NUMERICAL EXPERIMENT')
f=62;pr=cyclone_clf.predict_proba(Xs);fig,ax=plt.subplots(figsize=(6,4.2))
for c in [0,2,4,6,7]:
 ff,tt,_=roc_curve((ys==c).astype(int),pr[:,c]);ax.plot(ff,tt,lw=1.2,label=f'class {c} AUC={auc(ff,tt):.2f}')
ax.plot([0,1],[0,1],ls='--',lw=.8,color=SLATE);ax.set_xlabel('false-positive rate');ax.set_ylabel('true-positive rate');ax.legend(frameon=False,fontsize=7);clean(ax);fig.tight_layout();save(ch,f,fig);update(ch,f,'Controlled hurricane-classification ROC curves','One-vs-rest ROC curves computed from the probabilistic outputs of the same reproducible controlled eight-class hurricane-intensity classifier. Curves are shown for representative classes spanning the intensity range; AUC values are computed directly from held-out controlled data.','Pass 14 actual ROC calculation.','Random-forest controlled cyclone-intensity experiment; held-out probabilities.','CONTROLLED NUMERICAL EXPERIMENT')
print(f'Generated {len(rem)} Pass 14 figure(s) for this chapter.')
